name: test
on:
  push:
    branches-ignore: [main]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: { node-version: lts/*, cache: yarn }
      - name: Build
        run: |
          yarn install
          yarn build
